export interface WeaponItem {
  key: string;
  label: string;
}

export const WEAPONS_ITEMS: WeaponItem[] = [
  { key: 'roskM16',         label: 'רוס"ק M16' },
  { key: 'roskM4',          label: 'רוס"ק M4' },
  { key: 'negev',           label: 'נגב' },
  { key: 'mag',             label: 'מאג' },
  { key: 'matol',           label: 'מטול' },
  { key: 'baret',           label: 'בארט' },
  { key: 'trig',            label: 'טריג' },
  { key: 'm5',              label: 'כוונת M5' },
  { key: 'pictini',         label: 'פיקטיני' },
  { key: 'mepro',           label: 'מפרו' },
  { key: 'zayinNegev',      label: 'ציין נגב' },
  { key: 'shacha',          label: 'שח"ע' },
  { key: 'lior',            label: 'ליאור' },
  { key: 'zavon',           label: 'זאבון' },
  { key: 'akila6',          label: 'אקילה*6' },
  { key: 'binoculars',      label: 'משקפת' },
  { key: 'compass',         label: 'מצפן' },
  { key: 'armon',           label: 'ערמון' },
  { key: 'thermalMarker',   label: 'סמן טרמי לחיר' },
  { key: 'achbar',          label: 'עכבר' },
  { key: 'lpl',             label: 'LPL' },
  { key: 'yarour',          label: 'יראור' },
  { key: 'adi',             label: 'עדי' },
  { key: 'matolHandasi',    label: 'מט"ל הנדסי' },
  { key: 'matolSarug',      label: 'מט"ל סרוג' },
  { key: 'makabim',         label: 'מכבים' },
  { key: 'shabang',         label: 'שבנג' },
  { key: 'pagion',          label: 'פגיון' },
  { key: 'sightPagion',     label: 'כוונת לפגיון' },
  { key: 'ido',             label: 'עידו' },
  { key: 'leopold',         label: 'לאופולד' },
  { key: 'noa',             label: 'נועה' },
  { key: 'amit',            label: 'עמית' },
  { key: 'yarin',           label: 'ירין' },
  { key: 'shabshavet',      label: 'שבשבת' },
  { key: 'laserMatol',      label: 'סמן לייזר למטול' },
  { key: 'metzitzan',       label: 'מציצן' },
  { key: 'rigit',           label: 'ריגיט' },
  { key: 'magenOz',         label: 'מגן עוז' },
  { key: 'boresight',       label: 'בורסייט' },
  { key: 'kundson',         label: 'קונדסון' },
  { key: 'makhpal',         label: 'מכפל' },
  { key: 'negavon',         label: 'נגבון' },
  { key: 'pakZayinNegavon', label: 'פק ציין לנגבון' },
  { key: 'sightAyotek',     label: 'כוונת איוטק' },
  { key: 'binocularsPugi',  label: 'משקפת פוגי' },
  { key: 'ironBall',        label: 'כדור ברזל' },
  { key: 'mkh',             label: 'מק"ח' },
  { key: 'kneeNight',       label: 'ברך לילה' },
  { key: 'kneeDay',         label: 'ברך יום' },
  { key: 'merkavaCurtain',  label: 'וילון מרכבה' },
  { key: 'kitBaz',          label: 'ערכת באז' },
  { key: 'amaSoch',         label: 'אמה סוך' },
  { key: 'dotSmall',        label: 'נקודה קטנה' },
  { key: 'dotEnhanced',     label: 'נקודה משופרת' },
  { key: 'droneIbu',        label: 'רחפן איבו' },
  { key: 'droneAvatah',     label: 'רחפן אבטה' },
  { key: 'droneFlycard',    label: 'רחפן פלייקארד' },
  { key: 'robotRoni',       label: 'רובוט רוני' },
  { key: 'pinkLady',        label: 'פינק ליידי' },
  { key: 'robotAlon',       label: 'רובוט אלון' },
  { key: 'other',           label: 'אחר' },
];
